service: basic-serverless-lambda1

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src/handler.basic-serverless-lambda-1
    timeout: 60 # seconds
    memorySize: 128 # mb
